### ISSUE TITLE
Recording a subsection

### ISSUE THREAD

**Issue by telamon** [clabe45/vidar#51]
Hey, I'm writing an app that selects a 5 second section of a video and then encodes/exports it as a webm.
I couldn't find a layer that accepts a duration range. So i shifted my focus onto the `movie.record()` function.

Am I correct in assuming that the easiest way to add sub-section recording is to
Add a `start` and `end` options to `record()` and then
patch the function to start the background-movie playback at an offset using
`this.setCurrentTime(options.start)`
and then prematurely end the recording procedure on an `"movie.timeupdate"` event when `currentTime` exceeds `options.end` ?

**Comment by clabe45** [comment]
Hey, actually all layers should accept a `duration` option or argument\*. However, recording only a subsection of the entire movie is a great idea. Anyone can feel free to make a PR for this. `Movie#record` could take two (optional) options, probably `startTime` and `endTime` so they're consistent with the rest of the API.

\* In the latest release, all required arguments are passed as individual function parameters, but since this requires things like memorizing the parameter order, in the next release *every* argument will be passed through one `options` object. Currently, some layers *require* a duration so they accept it as an individual parameter to the function, while for other layers (such as `Video` and `Audio`), it is not required so it is passed through the options argument. Soon, it will be standardized into `options.duration` in every case. I will also document the process of migrating to the next version when it's released, so don't worry if this is confusing :smile:

**Comment by telamon** [comment]
Wow, thank you for adding this! :mage_man:
